# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='description default text'),
        ),
    ]
